
export enum AccountUserActionTypes {
    GET_ACCOUNT_USER_START = "GET_ACCOUNT_USER_START",
    GET_ACCOUNT_USER_SUCCESS = "GET_ACCOUNT_USER_SUCCESS",
    GET_ACCOUNT_USER_FAIL = "GET_ACCOUNT_USER_FAIL",

    GET_ORDER_HISTORY_START = "GET_ORDER_HISTORY_START",
    GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS",
    GET_ORDER_HISTORY_FAIL = "GET_ORDER_HISTORY_FAIL",
}
