
export enum RoomActionTypes {
    GET_ROOMS_START = "GET_ROOMS_START",
    GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS",
    GET_ROOMS_FAIL = "GET_ROOMS_FAIL",

    GET_ROOMS_BY_ID_START = "GET_ROOMS_BY_ID_START",
    GET_ROOMS_BY_ID_SUCCESS = "GET_ROOMS_BY_ID_SUCCESS",
    GET_ROOMS_BY_ID_FAIL = "GET_ROOMS_BY_ID_FAIL",
}
