
export enum AccountPriceListActionTypes {
    GET_ACCOUNT_PRICE_LIST_START = "GET_ACCOUNT_PRICE_LIST_START",
    GET_ACCOUNT_PRICE_LIST_SUCCESS = "GET_ACCOUNT_PRICE_LIST_SUCCESS",
    GET_ACCOUNT_PRICE_LIST_FAIL = "GET_ACCOUNT_PRICE_LIST_FAIL",

    GET_ACCOUNT_PRICE_LIST_BY_ID_START = "GET_ACCOUNT_PRICE_LIST_BY_ID_START",
    GET_ACCOUNT_PRICE_LIST_BY_ID_SUCCESS = "GET_ACCOUNT_PRICE_LIST_BY_ID_SUCCESS",
    GET_ACCOUNT_PRICE_LIST_BY_ID_FAIL = "GET_ACCOUNT_PRICE_LIST_BY_ID_FAIL",
}
