
export enum FeaturesActionTypes {
    GET_FEATURES_START = "GET_FEATURES_START",
    GET_FEATURES_SUCCESS = "GET_FEATURES_SUCCESS",
    GET_FEATURES_FAIL = "GET_FEATURES_FAIL",

    GET_FEATURES_ALL_START = "GET_FEATURES_ALL_START",
    GET_FEATURES_ALL_SUCCESS = "GET_FEATURES_ALL_SUCCESS",
    GET_FEATURES_ALL_FAIL = "GET_FEATURES_ALL_FAIL",

    GET_FEATURES_BY_ID_START = "GET_FEATURES_BY_ID_START",
    GET_FEATURES_BY_ID_SUCCESS = "GET_FEATURES_BY_ID_SUCCESS",
    GET_FEATURES_BY_ID_FAIL = "GET_FEATURES_BY_ID_FAIL",
}
