
export enum AccountActionTypes {
    GET_ACCOUNT_START = "GET_ACCOUNT_START",
    GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS",
    GET_ACCOUNT_FAIL = "GET_ACCOUNT_FAIL",

    GET_ACCOUNT_BY_ID_START = "GET_ACCOUNT_BY_ID_START",
    GET_ACCOUNT_BY_ID_SUCCESS = "GET_ACCOUNT_BY_ID_SUCCESS",
    GET_ACCOUNT_BY_ID_FAIL = "GET_ACCOUNT_BY_ID_FAIL",
}
