
export enum BrandActionTypes {
    GET_BRAND_START = "GET_BRAND_START",
    GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS",
    GET_BRAND_FAIL = "GET_BRAND_FAIL",

    GET_BRAND_BY_ID_START = "GET_BRAND_BY_ID_START",
    GET_BRAND_BY_ID_SUCCESS = "GET_BRAND_BY_ID_SUCCESS",
    GET_BRAND_BY_ID_FAIL = "GET_BRAND_BY_ID_FAIL",
}
