
export enum PromocodeActionTypes {
    GET_PROMOCODE_START = "GET_PROMOCODE_START",
    GET_PROMOCODE_SUCCESS = "GET_PROMOCODE_SUCCESS",
    GET_PROMOCODE_FAIL = "GET_PROMOCODE_FAIL",

    GET_PROMOCODE_BY_ID_START = "GET_PROMOCODE_BY_ID_START",
    GET_PROMOCODE_BY_ID_SUCCESS = "GET_PROMOCODE_BY_ID_SUCCESS",
    GET_PROMOCODE_BY_ID_FAIL = "GET_PROMOCODE_BY_ID_FAIL",



    GET_PAY_PROMOCODE_START = "GET_PAY_PROMOCODE_START",
}
